security:
  user:
    password: password
  basic:
    enabled: false
#  oauth2:
#    client:
#      client-id: demo
#      client-secret: demo
#      scope: read, write
#      auto-approve-scopes: .*
#    authorization:
#      check-token-access: permitAll()
server:
  port: 9999
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG